spring:
  application:
    name: cg
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/purchase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
server:
  servlet:
    context-path: /cg
  port: 81
